name: GitHub Actions Demo

on:
  push:
    branches: 
      - main
    paths-ignore: 
      - .github/**
  pull_request:
    branches:
      -main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  Build:
    name: Build my application
    runs-on: ubuntu-latest
    steps:
      - run: |
        echo 'Single quotes'
        echo "Double quotes"

      - uses: actions/checkout@v3.3.0

      - name: List files
